In [10]:
import pandas as pd

In [11]:
b_df = pd.read_csv("Bonedata.csv")
d_dict = {
    'd_1' : [],
    'd_2' : [],
    'd_3' : [],
    'd_4' : [],
    'd_5' : [],
    'd_6' : []
}
frames = []
values = b_df.columns
for i in range(0, len(values), 24):
    frame = list(values[i:i+24])
    if len(frame) < 24:
        break

    joints = []
    # 프레임 내부를 3개씩(x,y,z) 자르기 → 총 6개 관절
    for j in range(0, 24, 4):
        coord = frame[j:j+4]  # [x, y, z]
        joints.append(coord)

    frames.append(joints)

rows = []
for frame in frames:
    if len(frame) != 6:
        # 관절이 6개가 아니면 스킵하거나 예외 처리 (필요시 수정)
        continue
    row = []
    for triplet in frame:
        # triplet = [id, joint_name, coord_str]
        if len(triplet) != 4:
            # 형태가 다르면 스킵/보정
            continue
        
        a, b, c, d = triplet
        # 개행/보 BOM 등 정리 (원하는 경우)
        if isinstance(d, str):
            d = d.replace("\ufeff", "").split("\\n")[0]
        row.extend([str(b), str(c), str(d)])
    # 6관절 × 3값 = 18개
    if len(row) == 18:
        rows.append(row)

new_df = pd.DataFrame(rows)
new_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,330,clavicle_l,X=0.000 Y=0.000 Z=0.000,330.1,clavicle_r,X=3.022 Y=-2.052 Z=353.023,330.2,thigh_l,X=1.888 Y=0.644 Z=353.017,330.3,thigh_r,X=3.280 Y=-12.130 Z=304.069,330.4,calf_l,X=-5.405 Y=8.728 Z=303.637,330.5,calf_r,X=15.216 Y=-16.347 Z=260.103
1,331,clavicle_l.1,X=-7.522 Y=13.600 Z=258.195,331.1,clavicle_r.1,X=3.022 Y=-2.052 Z=353.023,331.2,thigh_l.1,X=1.888 Y=0.644 Z=353.017,331.3,thigh_r.1,X=3.280 Y=-12.130 Z=304.069,331.4,calf_l.1,X=-5.405 Y=8.728 Z=303.637,331.5,calf_r.1,X=15.216 Y=-16.347 Z=260.103
2,332,clavicle_l.2,X=-7.522 Y=13.600 Z=258.195,332.1,clavicle_r.2,X=3.022 Y=-2.052 Z=353.023,332.2,thigh_l.2,X=1.888 Y=0.644 Z=353.017,332.3,thigh_r.2,X=3.280 Y=-12.130 Z=304.069,332.4,calf_l.2,X=-5.405 Y=8.728 Z=303.637,332.5,calf_r.2,X=15.216 Y=-16.347 Z=260.103
3,333,clavicle_l.3,X=-7.522 Y=13.600 Z=258.195,333.1,clavicle_r.3,X=2.992 Y=-1.945 Z=353.070,333.2,thigh_l.3,X=1.849 Y=0.747 Z=353.061,333.3,thigh_r.3,X=3.372 Y=-12.020 Z=304.142,333.4,calf_l.3,X=-5.333 Y=8.829 Z=303.664,333.5,calf_r.3,X=15.170 Y=-16.298 Z=260.144
4,334,clavicle_l.4,X=-7.497 Y=13.648 Z=258.218,334.1,clavicle_r.4,X=2.941 Y=-1.916 Z=353.084,334.2,thigh_l.4,X=1.795 Y=0.775 Z=353.071,334.3,thigh_r.4,X=3.393 Y=-12.008 Z=304.156,334.4,calf_l.4,X=-5.315 Y=8.840 Z=303.671,334.5,calf_r.4,X=15.164 Y=-16.296 Z=260.152

In [12]:
new_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,330,clavicle_l,X=0.000 Y=0.000 Z=0.000,330.1,clavicle_r,X=3.022 Y=-2.052 Z=353.023,330.2,thigh_l,X=1.888 Y=0.644 Z=353.017,330.3,thigh_r,X=3.280 Y=-12.130 Z=304.069,330.4,calf_l,X=-5.405 Y=8.728 Z=303.637,330.5,calf_r,X=15.216 Y=-16.347 Z=260.103
1,331,clavicle_l.1,X=-7.522 Y=13.600 Z=258.195,331.1,clavicle_r.1,X=3.022 Y=-2.052 Z=353.023,331.2,thigh_l.1,X=1.888 Y=0.644 Z=353.017,331.3,thigh_r.1,X=3.280 Y=-12.130 Z=304.069,331.4,calf_l.1,X=-5.405 Y=8.728 Z=303.637,331.5,calf_r.1,X=15.216 Y=-16.347 Z=260.103
2,332,clavicle_l.2,X=-7.522 Y=13.600 Z=258.195,332.1,clavicle_r.2,X=3.022 Y=-2.052 Z=353.023,332.2,thigh_l.2,X=1.888 Y=0.644 Z=353.017,332.3,thigh_r.2,X=3.280 Y=-12.130 Z=304.069,332.4,calf_l.2,X=-5.405 Y=8.728 Z=303.637,332.5,calf_r.2,X=15.216 Y=-16.347 Z=260.103
3,333,clavicle_l.3,X=-7.522 Y=13.600 Z=258.195,333.1,clavicle_r.3,X=2.992 Y=-1.945 Z=353.070,333.2,thigh_l.3,X=1.849 Y=0.747 Z=353.061,333.3,thigh_r.3,X=3.372 Y=-12.020 Z=304.142,333.4,calf_l.3,X=-5.333 Y=8.829 Z=303.664,333.5,calf_r.3,X=15.170 Y=-16.298 Z=260.144
4,334,clavicle_l.4,X=-7.497 Y=13.648 Z=258.218,334.1,clavicle_r.4,X=2.941 Y=-1.916 Z=353.084,334.2,thigh_l.4,X=1.795 Y=0.775 Z=353.071,334.3,thigh_r.4,X=3.393 Y=-12.008 Z=304.156,334.4,calf_l.4,X=-5.315 Y=8.840 Z=303.671,334.5,calf_r.4,X=15.164 Y=-16.296 Z=260.152

In [13]:
reindex_dict = {
    'id' : [],
    'clavicle_l_x' : [],
    'clavicle_l_y' : [],
    'clavicle_l_z' : [],
    'clavicle_r_x' : [],
    'clavicle_r_y' : [],
    'clavicle_r_z' : [],
    'thigh_l_x' : [],
    'thigh_l_y' : [],
    'thigh_l_z' : [],
    'thigh_r_x' : [],
    'thigh_r_y' : [],
    'thigh_r_z' : [],
    'calf_l_x' : [],
    'calf_l_y' : [],
    'calf_l_z' : [],
    'calf_r_x' : [],
    'calf_r_y' : [],
    'calf_r_z' : []
}

def split_data(data):
    def check_n(s_n):
        n = float(s_n.split('=')[1])
        return round(n, 3)
    x, y, z = data.split(' ')
    return check_n(x), check_n(y), check_n(z)

for idx, row in new_df.iterrows():
    reindex_dict['id'].append(row[0])
    x, y, z = split_data(row[2])
    reindex_dict['clavicle_l_x'].append(x)
    reindex_dict['clavicle_l_y'].append(y)
    reindex_dict['clavicle_l_z'].append(z)
    x, y, z = split_data(row[5])
    reindex_dict['clavicle_r_x'].append(x)
    reindex_dict['clavicle_r_y'].append(y)
    reindex_dict['clavicle_r_z'].append(z)
    x, y, z = split_data(row[8])
    reindex_dict['thigh_l_x'].append(x)
    reindex_dict['thigh_l_y'].append(y)
    reindex_dict['thigh_l_z'].append(z)
    x, y, z = split_data(row[11])
    reindex_dict['thigh_r_x'].append(x)
    reindex_dict['thigh_r_y'].append(y)
    reindex_dict['thigh_r_z'].append(z)
    x, y, z = split_data(row[14])
    reindex_dict['calf_l_x'].append(x)
    reindex_dict['calf_l_y'].append(y)
    reindex_dict['calf_l_z'].append(z)
    x, y, z = split_data(row[17])
    reindex_dict['calf_r_x'].append(x)
    reindex_dict['calf_r_y'].append(y)
    reindex_dict['calf_r_z'].append(z)

In [14]:
f_df = pd.DataFrame(reindex_dict)
f_df

,id,clavicle_l_x,clavicle_l_y,clavicle_l_z,clavicle_r_x,clavicle_r_y,clavicle_r_z,thigh_l_x,thigh_l_y,thigh_l_z,thigh_r_x,thigh_r_y,thigh_r_z,calf_l_x,calf_l_y,calf_l_z,calf_r_x,calf_r_y,calf_r_z
0,330,0.000,0.000,0.000,3.022,-2.052,353.023,1.888,0.644,353.017,3.280,-12.130,304.069,-5.405,8.728,303.637,15.216,-16.347,260.103
1,331,-7.522,13.600,258.195,3.022,-2.052,353.023,1.888,0.644,353.017,3.280,-12.130,304.069,-5.405,8.728,303.637,15.216,-16.347,260.103
2,332,-7.522,13.600,258.195,3.022,-2.052,353.023,1.888,0.644,353.017,3.280,-12.130,304.069,-5.405,8.728,303.637,15.216,-16.347,260.103
3,333,-7.522,13.600,258.195,2.992,-1.945,353.070,1.849,0.747,353.061,3.372,-12.020,304.142,-5.333,8.829,303.664,15.170,-16.298,260.144
4,334,-7.497,13.648,258.218,2.941,-1.916,353.084,1.795,0.775,353.071,3.393,-12.008,304.156,-5.315,8.840,303.671,15.164,-16.296,260.152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677,007,1002.027,948.610,51.033,1007.361,992.107,137.181,1005.565,992.590,137.022,1017.610,977.049,89.473,995.295,978.182,88.935,1020.541,1009.034,56.770
678,008,1002.084,954.347,50.376,1007.404,997.322,136.788,1005.599,997.772,136.639,1017.609,982.160,89.102,995.288,983.219,88.629,1020.746,1013.219,55.537
679,009,1002.108,960.266,49.543,1007.410,1002.480,136.287,1005.595,1002.894,136.149,1017.607,987.190,88.715,995.287,988.199,88.123,1020.856,1017.271,54.282
680,010,1002.046,966.893,48.105,1007.415,1007.640,135.785,1005.592,1008.017,135.658,1017.605,992.220,88.328,995.286,993.180,87.618,1020.847,1020.906,52.724
681,011,1001.961,973.482,46.771,1007.419,1012.803,135.281,1005.588,1013.143,135.166,1017.602,997.250,87.941,995.286,998.161,87.112,1020.743,1024.135,50.949

In [15]:
f_df.to_csv('result.csv', index_label=False, index = False)

In [16]:
pd.read_csv('result.csv')

,id,clavicle_l_x,clavicle_l_y,clavicle_l_z,clavicle_r_x,clavicle_r_y,clavicle_r_z,thigh_l_x,thigh_l_y,thigh_l_z,thigh_r_x,thigh_r_y,thigh_r_z,calf_l_x,calf_l_y,calf_l_z,calf_r_x,calf_r_y,calf_r_z
0,330.0,0.000,0.000,0.000,3.022,-2.052,353.023,1.888,0.644,353.017,3.280,-12.130,304.069,-5.405,8.728,303.637,15.216,-16.347,260.103
1,331.0,-7.522,13.600,258.195,3.022,-2.052,353.023,1.888,0.644,353.017,3.280,-12.130,304.069,-5.405,8.728,303.637,15.216,-16.347,260.103
2,332.0,-7.522,13.600,258.195,3.022,-2.052,353.023,1.888,0.644,353.017,3.280,-12.130,304.069,-5.405,8.728,303.637,15.216,-16.347,260.103
3,333.0,-7.522,13.600,258.195,2.992,-1.945,353.070,1.849,0.747,353.061,3.372,-12.020,304.142,-5.333,8.829,303.664,15.170,-16.298,260.144
4,334.0,-7.497,13.648,258.218,2.941,-1.916,353.084,1.795,0.775,353.071,3.393,-12.008,304.156,-5.315,8.840,303.671,15.164,-16.296,260.152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677,7.0,1002.027,948.610,51.033,1007.361,992.107,137.181,1005.565,992.590,137.022,1017.610,977.049,89.473,995.295,978.182,88.935,1020.541,1009.034,56.770
678,8.0,1002.084,954.347,50.376,1007.404,997.322,136.788,1005.599,997.772,136.639,1017.609,982.160,89.102,995.288,983.219,88.629,1020.746,1013.219,55.537
679,9.0,1002.108,960.266,49.543,1007.410,1002.480,136.287,1005.595,1002.894,136.149,1017.607,987.190,88.715,995.287,988.199,88.123,1020.856,1017.271,54.282
680,10.0,1002.046,966.893,48.105,1007.415,1007.640,135.785,1005.592,1008.017,135.658,1017.605,992.220,88.328,995.286,993.180,87.618,1020.847,1020.906,52.724
681,11.0,1001.961,973.482,46.771,1007.419,1012.803,135.281,1005.588,1013.143,135.166,1017.602,997.250,87.941,995.286,998.161,87.112,1020.743,1024.135,50.949